Public Class FrmEdoCoahGame
    Dim resultado As Integer
    Public x As Integer

    Private Sub BtnBackPickMapEC_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles BtnBackPickMapEC.Click
        FrmPickMap.Show()
        Me.Hide()
    End Sub

    Private Sub FrmEdoCoahGame_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        ComboBox1.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox1.Items.Add("Nadadores")
        ComboBox1.Items.Add("Sierra Mojada")
        ComboBox1.Items.Add("Ocampo")
        ComboBox1.Items.Add("Candela")
        ComboBox1.Items.Add("Lamadrid")
        ComboBox1.Items.Add("Monclova")
        ComboBox1.Items.Add("Viesca")
        ComboBox1.Items.Add("Villa Unión")
        ComboBox1.Items.Add("Ciudad Acuña")
        ComboBox1.Items.Add("Francisco I.Madero")
        ComboBox1.Items.Add("General Cepeda")
        ComboBox1.Items.Add("Sacramento")
        ComboBox1.Items.Add("Progreso")
        ComboBox1.Items.Add("Juárez")
        ComboBox1.Items.Add("Nava")
        ComboBox1.Items.Add("Allende")
        ComboBox1.Items.Add("Hidalgo")
        ComboBox1.Items.Add("Torreón")
        ComboBox1.Items.Add("Zaragoza")
        ComboBox1.Items.Add("Jiménez")
        ComboBox1.Items.Add("Matamoros")
        ComboBox1.Items.Add("Arteaga")
        ComboBox1.Items.Add("Parras de la Fuente")
        ComboBox1.Items.Add("Abasolo")
        ComboBox1.Items.Add("Piedras Negras")
        ComboBox1.Items.Add("Ramos Arizpe")
        ComboBox1.Items.Add("San Pedro")
        ComboBox1.Items.Add("Morelos")
        ComboBox1.Items.Add("Guerrero")
        ComboBox1.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox1.Items.Add("Saltillo")
        ComboBox1.Items.Add("Escobedo")
        ComboBox1.Items.Add("Frontera")
        ComboBox1.Items.Add("Castaños")
        ComboBox1.Items.Add("Nueva Rosita")
        ComboBox1.Items.Add("Sabinas")
        ComboBox1.Items.Add("San Buenaventura")
        ComboBox2.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox2.Items.Add("Nadadores")
        ComboBox2.Items.Add("Sierra Mojada")
        ComboBox2.Items.Add("Ocampo")
        ComboBox2.Items.Add("Candela")
        ComboBox2.Items.Add("Lamadrid")
        ComboBox2.Items.Add("Monclova")
        ComboBox2.Items.Add("Viesca")
        ComboBox2.Items.Add("Villa Unión")
        ComboBox2.Items.Add("Ciudad Acuña")
        ComboBox2.Items.Add("Francisco I.Madero")
        ComboBox2.Items.Add("General Cepeda")
        ComboBox2.Items.Add("Sacramento")
        ComboBox2.Items.Add("Progreso")
        ComboBox2.Items.Add("Juárez")
        ComboBox2.Items.Add("Nava")
        ComboBox2.Items.Add("Allende")
        ComboBox2.Items.Add("Hidalgo")
        ComboBox2.Items.Add("Torreón")
        ComboBox2.Items.Add("Zaragoza")
        ComboBox2.Items.Add("Jiménez")
        ComboBox2.Items.Add("Matamoros")
        ComboBox2.Items.Add("Arteaga")
        ComboBox2.Items.Add("Parras de la Fuente")
        ComboBox2.Items.Add("Abasolo")
        ComboBox2.Items.Add("Piedras Negras")
        ComboBox2.Items.Add("Ramos Arizpe")
        ComboBox2.Items.Add("San Pedro")
        ComboBox2.Items.Add("Morelos")
        ComboBox2.Items.Add("Guerrero")
        ComboBox2.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox2.Items.Add("Saltillo")
        ComboBox2.Items.Add("Escobedo")
        ComboBox2.Items.Add("Frontera")
        ComboBox2.Items.Add("Castaños")
        ComboBox2.Items.Add("Nueva Rosita")
        ComboBox2.Items.Add("Sabinas")
        ComboBox2.Items.Add("San Buenaventura")
        ComboBox3.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox3.Items.Add("Nadadores")
        ComboBox3.Items.Add("Sierra Mojada")
        ComboBox3.Items.Add("Ocampo")
        ComboBox3.Items.Add("Candela")
        ComboBox3.Items.Add("Lamadrid")
        ComboBox3.Items.Add("Monclova")
        ComboBox3.Items.Add("Viesca")
        ComboBox3.Items.Add("Villa Unión")
        ComboBox3.Items.Add("Ciudad Acuña")
        ComboBox3.Items.Add("Francisco I.Madero")
        ComboBox3.Items.Add("General Cepeda")
        ComboBox3.Items.Add("Sacramento")
        ComboBox3.Items.Add("Progreso")
        ComboBox3.Items.Add("Juárez")
        ComboBox3.Items.Add("Nava")
        ComboBox3.Items.Add("Allende")
        ComboBox3.Items.Add("Hidalgo")
        ComboBox3.Items.Add("Torreón")
        ComboBox3.Items.Add("Zaragoza")
        ComboBox3.Items.Add("Jiménez")
        ComboBox3.Items.Add("Matamoros")
        ComboBox3.Items.Add("Arteaga")
        ComboBox3.Items.Add("Parras de la Fuente")
        ComboBox3.Items.Add("Abasolo")
        ComboBox3.Items.Add("Piedras Negras")
        ComboBox3.Items.Add("Ramos Arizpe")
        ComboBox3.Items.Add("San Pedro")
        ComboBox3.Items.Add("Morelos")
        ComboBox3.Items.Add("Guerrero")
        ComboBox3.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox3.Items.Add("Saltillo")
        ComboBox3.Items.Add("Escobedo")
        ComboBox3.Items.Add("Frontera")
        ComboBox3.Items.Add("Castaños")
        ComboBox3.Items.Add("Nueva Rosita")
        ComboBox3.Items.Add("Sabinas")
        ComboBox3.Items.Add("San Buenaventura")
        ComboBox4.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox4.Items.Add("Nadadores")
        ComboBox4.Items.Add("Sierra Mojada")
        ComboBox4.Items.Add("Ocampo")
        ComboBox4.Items.Add("Candela")
        ComboBox4.Items.Add("Lamadrid")
        ComboBox4.Items.Add("Monclova")
        ComboBox4.Items.Add("Viesca")
        ComboBox4.Items.Add("Villa Unión")
        ComboBox4.Items.Add("Ciudad Acuña")
        ComboBox4.Items.Add("Francisco I.Madero")
        ComboBox4.Items.Add("General Cepeda")
        ComboBox4.Items.Add("Sacramento")
        ComboBox4.Items.Add("Progreso")
        ComboBox4.Items.Add("Juárez")
        ComboBox4.Items.Add("Nava")
        ComboBox4.Items.Add("Allende")
        ComboBox4.Items.Add("Hidalgo")
        ComboBox4.Items.Add("Torreón")
        ComboBox4.Items.Add("Zaragoza")
        ComboBox4.Items.Add("Jiménez")
        ComboBox4.Items.Add("Matamoros")
        ComboBox4.Items.Add("Arteaga")
        ComboBox4.Items.Add("Parras de la Fuente")
        ComboBox4.Items.Add("Abasolo")
        ComboBox4.Items.Add("Piedras Negras")
        ComboBox4.Items.Add("Ramos Arizpe")
        ComboBox4.Items.Add("San Pedro")
        ComboBox4.Items.Add("Morelos")
        ComboBox4.Items.Add("Guerrero")
        ComboBox4.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox4.Items.Add("Saltillo")
        ComboBox4.Items.Add("Escobedo")
        ComboBox4.Items.Add("Frontera")
        ComboBox4.Items.Add("Castaños")
        ComboBox4.Items.Add("Nueva Rosita")
        ComboBox4.Items.Add("Sabinas")
        ComboBox4.Items.Add("San Buenaventura")
        ComboBox5.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox5.Items.Add("Nadadores")
        ComboBox5.Items.Add("Sierra Mojada")
        ComboBox5.Items.Add("Ocampo")
        ComboBox5.Items.Add("Candela")
        ComboBox5.Items.Add("Lamadrid")
        ComboBox5.Items.Add("Monclova")
        ComboBox5.Items.Add("Viesca")
        ComboBox5.Items.Add("Villa Unión")
        ComboBox5.Items.Add("Ciudad Acuña")
        ComboBox5.Items.Add("Francisco I.Madero")
        ComboBox5.Items.Add("General Cepeda")
        ComboBox5.Items.Add("Sacramento")
        ComboBox5.Items.Add("Progreso")
        ComboBox5.Items.Add("Juárez")
        ComboBox5.Items.Add("Nava")
        ComboBox5.Items.Add("Allende")
        ComboBox5.Items.Add("Hidalgo")
        ComboBox5.Items.Add("Torreón")
        ComboBox5.Items.Add("Zaragoza")
        ComboBox5.Items.Add("Jiménez")
        ComboBox5.Items.Add("Matamoros")
        ComboBox5.Items.Add("Arteaga")
        ComboBox5.Items.Add("Parras de la Fuente")
        ComboBox5.Items.Add("Abasolo")
        ComboBox5.Items.Add("Piedras Negras")
        ComboBox5.Items.Add("Ramos Arizpe")
        ComboBox5.Items.Add("San Pedro")
        ComboBox5.Items.Add("Morelos")
        ComboBox5.Items.Add("Guerrero")
        ComboBox5.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox5.Items.Add("Saltillo")
        ComboBox5.Items.Add("Escobedo")
        ComboBox5.Items.Add("Frontera")
        ComboBox5.Items.Add("Castaños")
        ComboBox5.Items.Add("Nueva Rosita")
        ComboBox5.Items.Add("Sabinas")
        ComboBox5.Items.Add("San Buenaventura")
        ComboBox6.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox6.Items.Add("Nadadores")
        ComboBox6.Items.Add("Sierra Mojada")
        ComboBox6.Items.Add("Ocampo")
        ComboBox6.Items.Add("Candela")
        ComboBox6.Items.Add("Lamadrid")
        ComboBox6.Items.Add("Monclova")
        ComboBox6.Items.Add("Viesca")
        ComboBox6.Items.Add("Villa Unión")
        ComboBox6.Items.Add("Ciudad Acuña")
        ComboBox6.Items.Add("Francisco I.Madero")
        ComboBox6.Items.Add("General Cepeda")
        ComboBox6.Items.Add("Sacramento")
        ComboBox6.Items.Add("Progreso")
        ComboBox6.Items.Add("Juárez")
        ComboBox6.Items.Add("Nava")
        ComboBox6.Items.Add("Allende")
        ComboBox6.Items.Add("Hidalgo")
        ComboBox6.Items.Add("Torreón")
        ComboBox6.Items.Add("Zaragoza")
        ComboBox6.Items.Add("Jiménez")
        ComboBox6.Items.Add("Matamoros")
        ComboBox6.Items.Add("Arteaga")
        ComboBox6.Items.Add("Parras de la Fuente")
        ComboBox6.Items.Add("Abasolo")
        ComboBox6.Items.Add("Piedras Negras")
        ComboBox6.Items.Add("Ramos Arizpe")
        ComboBox6.Items.Add("San Pedro")
        ComboBox6.Items.Add("Morelos")
        ComboBox6.Items.Add("Guerrero")
        ComboBox6.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox6.Items.Add("Saltillo")
        ComboBox6.Items.Add("Escobedo")
        ComboBox6.Items.Add("Frontera")
        ComboBox6.Items.Add("Castaños")
        ComboBox6.Items.Add("Nueva Rosita")
        ComboBox6.Items.Add("Sabinas")
        ComboBox6.Items.Add("San Buenaventura")
        ComboBox7.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox7.Items.Add("Nadadores")
        ComboBox7.Items.Add("Sierra Mojada")
        ComboBox7.Items.Add("Ocampo")
        ComboBox7.Items.Add("Candela")
        ComboBox7.Items.Add("Lamadrid")
        ComboBox7.Items.Add("Monclova")
        ComboBox7.Items.Add("Viesca")
        ComboBox7.Items.Add("Villa Unión")
        ComboBox7.Items.Add("Ciudad Acuña")
        ComboBox7.Items.Add("Francisco I.Madero")
        ComboBox7.Items.Add("General Cepeda")
        ComboBox7.Items.Add("Sacramento")
        ComboBox7.Items.Add("Progreso")
        ComboBox7.Items.Add("Juárez")
        ComboBox7.Items.Add("Nava")
        ComboBox7.Items.Add("Allende")
        ComboBox7.Items.Add("Hidalgo")
        ComboBox7.Items.Add("Torreón")
        ComboBox7.Items.Add("Zaragoza")
        ComboBox7.Items.Add("Jiménez")
        ComboBox7.Items.Add("Matamoros")
        ComboBox7.Items.Add("Arteaga")
        ComboBox7.Items.Add("Parras de la Fuente")
        ComboBox7.Items.Add("Abasolo")
        ComboBox7.Items.Add("Piedras Negras")
        ComboBox7.Items.Add("Ramos Arizpe")
        ComboBox7.Items.Add("San Pedro")
        ComboBox7.Items.Add("Morelos")
        ComboBox7.Items.Add("Guerrero")
        ComboBox7.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox7.Items.Add("Saltillo")
        ComboBox7.Items.Add("Escobedo")
        ComboBox7.Items.Add("Frontera")
        ComboBox7.Items.Add("Castaños")
        ComboBox7.Items.Add("Nueva Rosita")
        ComboBox7.Items.Add("Sabinas")
        ComboBox7.Items.Add("San Buenaventura")
        ComboBox8.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox8.Items.Add("Nadadores")
        ComboBox8.Items.Add("Sierra Mojada")
        ComboBox8.Items.Add("Ocampo")
        ComboBox8.Items.Add("Candela")
        ComboBox8.Items.Add("Lamadrid")
        ComboBox8.Items.Add("Monclova")
        ComboBox8.Items.Add("Viesca")
        ComboBox8.Items.Add("Villa Unión")
        ComboBox8.Items.Add("Ciudad Acuña")
        ComboBox8.Items.Add("Francisco I.Madero")
        ComboBox8.Items.Add("General Cepeda")
        ComboBox8.Items.Add("Sacramento")
        ComboBox8.Items.Add("Progreso")
        ComboBox8.Items.Add("Juárez")
        ComboBox8.Items.Add("Nava")
        ComboBox8.Items.Add("Allende")
        ComboBox8.Items.Add("Hidalgo")
        ComboBox8.Items.Add("Torreón")
        ComboBox8.Items.Add("Zaragoza")
        ComboBox8.Items.Add("Jiménez")
        ComboBox8.Items.Add("Matamoros")
        ComboBox8.Items.Add("Arteaga")
        ComboBox8.Items.Add("Parras de la Fuente")
        ComboBox8.Items.Add("Abasolo")
        ComboBox8.Items.Add("Piedras Negras")
        ComboBox8.Items.Add("Ramos Arizpe")
        ComboBox8.Items.Add("San Pedro")
        ComboBox8.Items.Add("Morelos")
        ComboBox8.Items.Add("Guerrero")
        ComboBox8.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox8.Items.Add("Saltillo")
        ComboBox8.Items.Add("Escobedo")
        ComboBox8.Items.Add("Frontera")
        ComboBox8.Items.Add("Castaños")
        ComboBox8.Items.Add("Nueva Rosita")
        ComboBox8.Items.Add("Sabinas")
        ComboBox8.Items.Add("San Buenaventura")
        ComboBox9.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox9.Items.Add("Nadadores")
        ComboBox9.Items.Add("Sierra Mojada")
        ComboBox9.Items.Add("Ocampo")
        ComboBox9.Items.Add("Candela")
        ComboBox9.Items.Add("Lamadrid")
        ComboBox9.Items.Add("Monclova")
        ComboBox9.Items.Add("Viesca")
        ComboBox9.Items.Add("Villa Unión")
        ComboBox9.Items.Add("Ciudad Acuña")
        ComboBox9.Items.Add("Francisco I.Madero")
        ComboBox9.Items.Add("General Cepeda")
        ComboBox9.Items.Add("Sacramento")
        ComboBox9.Items.Add("Progreso")
        ComboBox9.Items.Add("Juárez")
        ComboBox9.Items.Add("Nava")
        ComboBox9.Items.Add("Allende")
        ComboBox9.Items.Add("Hidalgo")
        ComboBox9.Items.Add("Torreón")
        ComboBox9.Items.Add("Zaragoza")
        ComboBox9.Items.Add("Jiménez")
        ComboBox9.Items.Add("Matamoros")
        ComboBox9.Items.Add("Arteaga")
        ComboBox9.Items.Add("Parras de la Fuente")
        ComboBox9.Items.Add("Abasolo")
        ComboBox9.Items.Add("Piedras Negras")
        ComboBox9.Items.Add("Ramos Arizpe")
        ComboBox9.Items.Add("San Pedro")
        ComboBox9.Items.Add("Morelos")
        ComboBox9.Items.Add("Guerrero")
        ComboBox9.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox9.Items.Add("Saltillo")
        ComboBox9.Items.Add("Escobedo")
        ComboBox9.Items.Add("Frontera")
        ComboBox9.Items.Add("Castaños")
        ComboBox9.Items.Add("Nueva Rosita")
        ComboBox9.Items.Add("Sabinas")
        ComboBox9.Items.Add("San Buenaventura")
        ComboBox10.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox10.Items.Add("Nadadores")
        ComboBox10.Items.Add("Sierra Mojada")
        ComboBox10.Items.Add("Ocampo")
        ComboBox10.Items.Add("Candela")
        ComboBox10.Items.Add("Lamadrid")
        ComboBox10.Items.Add("Monclova")
        ComboBox10.Items.Add("Viesca")
        ComboBox10.Items.Add("Villa Unión")
        ComboBox10.Items.Add("Ciudad Acuña")
        ComboBox10.Items.Add("Francisco I.Madero")
        ComboBox10.Items.Add("General Cepeda")
        ComboBox10.Items.Add("Sacramento")
        ComboBox10.Items.Add("Progreso")
        ComboBox10.Items.Add("Juárez")
        ComboBox10.Items.Add("Nava")
        ComboBox10.Items.Add("Allende")
        ComboBox10.Items.Add("Hidalgo")
        ComboBox10.Items.Add("Torreón")
        ComboBox10.Items.Add("Zaragoza")
        ComboBox10.Items.Add("Jiménez")
        ComboBox10.Items.Add("Matamoros")
        ComboBox10.Items.Add("Arteaga")
        ComboBox10.Items.Add("Parras de la Fuente")
        ComboBox10.Items.Add("Abasolo")
        ComboBox10.Items.Add("Piedras Negras")
        ComboBox10.Items.Add("Ramos Arizpe")
        ComboBox10.Items.Add("San Pedro")
        ComboBox10.Items.Add("Morelos")
        ComboBox10.Items.Add("Guerrero")
        ComboBox10.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox10.Items.Add("Saltillo")
        ComboBox10.Items.Add("Escobedo")
        ComboBox10.Items.Add("Frontera")
        ComboBox10.Items.Add("Castaños")
        ComboBox10.Items.Add("Nueva Rosita")
        ComboBox10.Items.Add("Sabinas")
        ComboBox10.Items.Add("San Buenaventura")
        ComboBox11.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox11.Items.Add("Nadadores")
        ComboBox11.Items.Add("Sierra Mojada")
        ComboBox11.Items.Add("Ocampo")
        ComboBox11.Items.Add("Candela")
        ComboBox11.Items.Add("Lamadrid")
        ComboBox11.Items.Add("Monclova")
        ComboBox11.Items.Add("Viesca")
        ComboBox11.Items.Add("Villa Unión")
        ComboBox11.Items.Add("Ciudad Acuña")
        ComboBox11.Items.Add("Francisco I.Madero")
        ComboBox11.Items.Add("General Cepeda")
        ComboBox11.Items.Add("Sacramento")
        ComboBox11.Items.Add("Progreso")
        ComboBox11.Items.Add("Juárez")
        ComboBox11.Items.Add("Nava")
        ComboBox11.Items.Add("Allende")
        ComboBox11.Items.Add("Hidalgo")
        ComboBox11.Items.Add("Torreón")
        ComboBox11.Items.Add("Zaragoza")
        ComboBox11.Items.Add("Jiménez")
        ComboBox11.Items.Add("Matamoros")
        ComboBox11.Items.Add("Arteaga")
        ComboBox11.Items.Add("Parras de la Fuente")
        ComboBox11.Items.Add("Abasolo")
        ComboBox11.Items.Add("Piedras Negras")
        ComboBox11.Items.Add("Ramos Arizpe")
        ComboBox11.Items.Add("San Pedro")
        ComboBox11.Items.Add("Morelos")
        ComboBox11.Items.Add("Guerrero")
        ComboBox11.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox11.Items.Add("Saltillo")
        ComboBox11.Items.Add("Escobedo")
        ComboBox11.Items.Add("Frontera")
        ComboBox11.Items.Add("Castaños")
        ComboBox11.Items.Add("Nueva Rosita")
        ComboBox11.Items.Add("Sabinas")
        ComboBox11.Items.Add("San Buenaventura")
        ComboBox12.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox12.Items.Add("Nadadores")
        ComboBox12.Items.Add("Sierra Mojada")
        ComboBox12.Items.Add("Ocampo")
        ComboBox12.Items.Add("Candela")
        ComboBox12.Items.Add("Lamadrid")
        ComboBox12.Items.Add("Monclova")
        ComboBox12.Items.Add("Viesca")
        ComboBox12.Items.Add("Villa Unión")
        ComboBox12.Items.Add("Ciudad Acuña")
        ComboBox12.Items.Add("Francisco I.Madero")
        ComboBox12.Items.Add("General Cepeda")
        ComboBox12.Items.Add("Sacramento")
        ComboBox12.Items.Add("Progreso")
        ComboBox12.Items.Add("Juárez")
        ComboBox12.Items.Add("Nava")
        ComboBox12.Items.Add("Allende")
        ComboBox12.Items.Add("Hidalgo")
        ComboBox12.Items.Add("Torreón")
        ComboBox12.Items.Add("Zaragoza")
        ComboBox12.Items.Add("Jiménez")
        ComboBox12.Items.Add("Matamoros")
        ComboBox12.Items.Add("Arteaga")
        ComboBox12.Items.Add("Parras de la Fuente")
        ComboBox12.Items.Add("Abasolo")
        ComboBox12.Items.Add("Piedras Negras")
        ComboBox12.Items.Add("Ramos Arizpe")
        ComboBox12.Items.Add("San Pedro")
        ComboBox12.Items.Add("Morelos")
        ComboBox12.Items.Add("Guerrero")
        ComboBox12.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox12.Items.Add("Saltillo")
        ComboBox12.Items.Add("Escobedo")
        ComboBox12.Items.Add("Frontera")
        ComboBox12.Items.Add("Castaños")
        ComboBox12.Items.Add("Nueva Rosita")
        ComboBox12.Items.Add("Sabinas")
        ComboBox12.Items.Add("San Buenaventura")
        ComboBox13.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox13.Items.Add("Nadadores")
        ComboBox13.Items.Add("Sierra Mojada")
        ComboBox13.Items.Add("Ocampo")
        ComboBox13.Items.Add("Candela")
        ComboBox13.Items.Add("Lamadrid")
        ComboBox13.Items.Add("Monclova")
        ComboBox13.Items.Add("Viesca")
        ComboBox13.Items.Add("Villa Unión")
        ComboBox13.Items.Add("Ciudad Acuña")
        ComboBox13.Items.Add("Francisco I.Madero")
        ComboBox13.Items.Add("General Cepeda")
        ComboBox13.Items.Add("Sacramento")
        ComboBox13.Items.Add("Progreso")
        ComboBox13.Items.Add("Juárez")
        ComboBox13.Items.Add("Nava")
        ComboBox13.Items.Add("Allende")
        ComboBox13.Items.Add("Hidalgo")
        ComboBox13.Items.Add("Torreón")
        ComboBox13.Items.Add("Zaragoza")
        ComboBox13.Items.Add("Jiménez")
        ComboBox13.Items.Add("Matamoros")
        ComboBox13.Items.Add("Arteaga")
        ComboBox13.Items.Add("Parras de la Fuente")
        ComboBox13.Items.Add("Abasolo")
        ComboBox13.Items.Add("Piedras Negras")
        ComboBox13.Items.Add("Ramos Arizpe")
        ComboBox13.Items.Add("San Pedro")
        ComboBox13.Items.Add("Morelos")
        ComboBox13.Items.Add("Guerrero")
        ComboBox13.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox13.Items.Add("Saltillo")
        ComboBox13.Items.Add("Escobedo")
        ComboBox13.Items.Add("Frontera")
        ComboBox13.Items.Add("Castaños")
        ComboBox13.Items.Add("Nueva Rosita")
        ComboBox13.Items.Add("Sabinas")
        ComboBox13.Items.Add("San Buenaventura")
        ComboBox14.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox14.Items.Add("Nadadores")
        ComboBox14.Items.Add("Sierra Mojada")
        ComboBox14.Items.Add("Ocampo")
        ComboBox14.Items.Add("Candela")
        ComboBox14.Items.Add("Lamadrid")
        ComboBox14.Items.Add("Monclova")
        ComboBox14.Items.Add("Viesca")
        ComboBox14.Items.Add("Villa Unión")
        ComboBox14.Items.Add("Ciudad Acuña")
        ComboBox14.Items.Add("Francisco I.Madero")
        ComboBox14.Items.Add("General Cepeda")
        ComboBox14.Items.Add("Sacramento")
        ComboBox14.Items.Add("Progreso")
        ComboBox14.Items.Add("Juárez")
        ComboBox14.Items.Add("Nava")
        ComboBox14.Items.Add("Allende")
        ComboBox14.Items.Add("Hidalgo")
        ComboBox14.Items.Add("Torreón")
        ComboBox14.Items.Add("Zaragoza")
        ComboBox14.Items.Add("Jiménez")
        ComboBox14.Items.Add("Matamoros")
        ComboBox14.Items.Add("Arteaga")
        ComboBox14.Items.Add("Parras de la Fuente")
        ComboBox14.Items.Add("Abasolo")
        ComboBox14.Items.Add("Piedras Negras")
        ComboBox14.Items.Add("Ramos Arizpe")
        ComboBox14.Items.Add("San Pedro")
        ComboBox14.Items.Add("Morelos")
        ComboBox14.Items.Add("Guerrero")
        ComboBox14.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox14.Items.Add("Saltillo")
        ComboBox14.Items.Add("Escobedo")
        ComboBox14.Items.Add("Frontera")
        ComboBox14.Items.Add("Castaños")
        ComboBox14.Items.Add("Nueva Rosita")
        ComboBox14.Items.Add("Sabinas")
        ComboBox14.Items.Add("San Buenaventura")
        ComboBox15.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox15.Items.Add("Nadadores")
        ComboBox15.Items.Add("Sierra Mojada")
        ComboBox15.Items.Add("Ocampo")
        ComboBox15.Items.Add("Candela")
        ComboBox15.Items.Add("Lamadrid")
        ComboBox15.Items.Add("Monclova")
        ComboBox15.Items.Add("Viesca")
        ComboBox15.Items.Add("Villa Unión")
        ComboBox15.Items.Add("Ciudad Acuña")
        ComboBox15.Items.Add("Francisco I.Madero")
        ComboBox15.Items.Add("General Cepeda")
        ComboBox15.Items.Add("Sacramento")
        ComboBox15.Items.Add("Progreso")
        ComboBox15.Items.Add("Juárez")
        ComboBox15.Items.Add("Nava")
        ComboBox15.Items.Add("Allende")
        ComboBox15.Items.Add("Hidalgo")
        ComboBox15.Items.Add("Torreón")
        ComboBox15.Items.Add("Zaragoza")
        ComboBox15.Items.Add("Jiménez")
        ComboBox15.Items.Add("Matamoros")
        ComboBox15.Items.Add("Arteaga")
        ComboBox15.Items.Add("Parras de la Fuente")
        ComboBox15.Items.Add("Abasolo")
        ComboBox15.Items.Add("Piedras Negras")
        ComboBox15.Items.Add("Ramos Arizpe")
        ComboBox15.Items.Add("San Pedro")
        ComboBox15.Items.Add("Morelos")
        ComboBox15.Items.Add("Guerrero")
        ComboBox15.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox15.Items.Add("Saltillo")
        ComboBox15.Items.Add("Escobedo")
        ComboBox15.Items.Add("Frontera")
        ComboBox15.Items.Add("Castaños")
        ComboBox15.Items.Add("Nueva Rosita")
        ComboBox15.Items.Add("Sabinas")
        ComboBox15.Items.Add("San Buenaventura")
        ComboBox16.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox16.Items.Add("Nadadores")
        ComboBox16.Items.Add("Sierra Mojada")
        ComboBox16.Items.Add("Ocampo")
        ComboBox16.Items.Add("Candela")
        ComboBox16.Items.Add("Lamadrid")
        ComboBox16.Items.Add("Monclova")
        ComboBox16.Items.Add("Viesca")
        ComboBox16.Items.Add("Villa Unión")
        ComboBox16.Items.Add("Ciudad Acuña")
        ComboBox16.Items.Add("Francisco I.Madero")
        ComboBox16.Items.Add("General Cepeda")
        ComboBox16.Items.Add("Sacramento")
        ComboBox16.Items.Add("Progreso")
        ComboBox16.Items.Add("Juárez")
        ComboBox16.Items.Add("Nava")
        ComboBox16.Items.Add("Allende")
        ComboBox16.Items.Add("Hidalgo")
        ComboBox16.Items.Add("Torreón")
        ComboBox16.Items.Add("Zaragoza")
        ComboBox16.Items.Add("Jiménez")
        ComboBox16.Items.Add("Matamoros")
        ComboBox16.Items.Add("Arteaga")
        ComboBox16.Items.Add("Parras de la Fuente")
        ComboBox16.Items.Add("Abasolo")
        ComboBox16.Items.Add("Piedras Negras")
        ComboBox16.Items.Add("Ramos Arizpe")
        ComboBox16.Items.Add("San Pedro")
        ComboBox16.Items.Add("Morelos")
        ComboBox16.Items.Add("Guerrero")
        ComboBox16.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox16.Items.Add("Saltillo")
        ComboBox16.Items.Add("Escobedo")
        ComboBox16.Items.Add("Frontera")
        ComboBox16.Items.Add("Castaños")
        ComboBox16.Items.Add("Nueva Rosita")
        ComboBox16.Items.Add("Sabinas")
        ComboBox16.Items.Add("San Buenaventura")
        ComboBox17.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox17.Items.Add("Nadadores")
        ComboBox17.Items.Add("Sierra Mojada")
        ComboBox17.Items.Add("Ocampo")
        ComboBox17.Items.Add("Candela")
        ComboBox17.Items.Add("Lamadrid")
        ComboBox17.Items.Add("Monclova")
        ComboBox17.Items.Add("Viesca")
        ComboBox17.Items.Add("Villa Unión")
        ComboBox17.Items.Add("Ciudad Acuña")
        ComboBox17.Items.Add("Francisco I.Madero")
        ComboBox17.Items.Add("General Cepeda")
        ComboBox17.Items.Add("Sacramento")
        ComboBox17.Items.Add("Progreso")
        ComboBox17.Items.Add("Juárez")
        ComboBox17.Items.Add("Nava")
        ComboBox17.Items.Add("Allende")
        ComboBox17.Items.Add("Hidalgo")
        ComboBox17.Items.Add("Torreón")
        ComboBox17.Items.Add("Zaragoza")
        ComboBox17.Items.Add("Jiménez")
        ComboBox17.Items.Add("Matamoros")
        ComboBox17.Items.Add("Arteaga")
        ComboBox17.Items.Add("Parras de la Fuente")
        ComboBox17.Items.Add("Abasolo")
        ComboBox17.Items.Add("Piedras Negras")
        ComboBox17.Items.Add("Ramos Arizpe")
        ComboBox17.Items.Add("San Pedro")
        ComboBox17.Items.Add("Morelos")
        ComboBox17.Items.Add("Guerrero")
        ComboBox17.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox17.Items.Add("Saltillo")
        ComboBox17.Items.Add("Escobedo")
        ComboBox17.Items.Add("Frontera")
        ComboBox17.Items.Add("Castaños")
        ComboBox17.Items.Add("Nueva Rosita")
        ComboBox17.Items.Add("Sabinas")
        ComboBox17.Items.Add("San Buenaventura")
        ComboBox18.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox18.Items.Add("Nadadores")
        ComboBox18.Items.Add("Sierra Mojada")
        ComboBox18.Items.Add("Ocampo")
        ComboBox18.Items.Add("Candela")
        ComboBox18.Items.Add("Lamadrid")
        ComboBox18.Items.Add("Monclova")
        ComboBox18.Items.Add("Viesca")
        ComboBox18.Items.Add("Villa Unión")
        ComboBox18.Items.Add("Ciudad Acuña")
        ComboBox18.Items.Add("Francisco I.Madero")
        ComboBox18.Items.Add("General Cepeda")
        ComboBox18.Items.Add("Sacramento")
        ComboBox18.Items.Add("Progreso")
        ComboBox18.Items.Add("Juárez")
        ComboBox18.Items.Add("Nava")
        ComboBox18.Items.Add("Allende")
        ComboBox18.Items.Add("Hidalgo")
        ComboBox18.Items.Add("Torreón")
        ComboBox18.Items.Add("Zaragoza")
        ComboBox18.Items.Add("Jiménez")
        ComboBox18.Items.Add("Matamoros")
        ComboBox18.Items.Add("Arteaga")
        ComboBox18.Items.Add("Parras de la Fuente")
        ComboBox18.Items.Add("Abasolo")
        ComboBox18.Items.Add("Piedras Negras")
        ComboBox18.Items.Add("Ramos Arizpe")
        ComboBox18.Items.Add("San Pedro")
        ComboBox18.Items.Add("Morelos")
        ComboBox18.Items.Add("Guerrero")
        ComboBox18.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox18.Items.Add("Saltillo")
        ComboBox18.Items.Add("Escobedo")
        ComboBox18.Items.Add("Frontera")
        ComboBox18.Items.Add("Castaños")
        ComboBox18.Items.Add("Nueva Rosita")
        ComboBox18.Items.Add("Sabinas")
        ComboBox18.Items.Add("San Buenaventura")
        ComboBox19.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox19.Items.Add("Nadadores")
        ComboBox19.Items.Add("Sierra Mojada")
        ComboBox19.Items.Add("Ocampo")
        ComboBox19.Items.Add("Candela")
        ComboBox19.Items.Add("Lamadrid")
        ComboBox19.Items.Add("Monclova")
        ComboBox19.Items.Add("Viesca")
        ComboBox19.Items.Add("Villa Unión")
        ComboBox19.Items.Add("Ciudad Acuña")
        ComboBox19.Items.Add("Francisco I.Madero")
        ComboBox19.Items.Add("General Cepeda")
        ComboBox19.Items.Add("Sacramento")
        ComboBox19.Items.Add("Progreso")
        ComboBox19.Items.Add("Juárez")
        ComboBox19.Items.Add("Nava")
        ComboBox19.Items.Add("Allende")
        ComboBox19.Items.Add("Hidalgo")
        ComboBox19.Items.Add("Torreón")
        ComboBox19.Items.Add("Zaragoza")
        ComboBox19.Items.Add("Jiménez")
        ComboBox19.Items.Add("Matamoros")
        ComboBox19.Items.Add("Arteaga")
        ComboBox19.Items.Add("Parras de la Fuente")
        ComboBox19.Items.Add("Abasolo")
        ComboBox19.Items.Add("Piedras Negras")
        ComboBox19.Items.Add("Ramos Arizpe")
        ComboBox19.Items.Add("San Pedro")
        ComboBox19.Items.Add("Morelos")
        ComboBox19.Items.Add("Guerrero")
        ComboBox19.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox19.Items.Add("Saltillo")
        ComboBox19.Items.Add("Escobedo")
        ComboBox19.Items.Add("Frontera")
        ComboBox19.Items.Add("Castaños")
        ComboBox19.Items.Add("Nueva Rosita")
        ComboBox19.Items.Add("Sabinas")
        ComboBox19.Items.Add("San Buenaventura")
        ComboBox20.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox20.Items.Add("Nadadores")
        ComboBox20.Items.Add("Sierra Mojada")
        ComboBox20.Items.Add("Ocampo")
        ComboBox20.Items.Add("Candela")
        ComboBox20.Items.Add("Lamadrid")
        ComboBox20.Items.Add("Monclova")
        ComboBox20.Items.Add("Viesca")
        ComboBox20.Items.Add("Villa Unión")
        ComboBox20.Items.Add("Ciudad Acuña")
        ComboBox20.Items.Add("Francisco I.Madero")
        ComboBox20.Items.Add("General Cepeda")
        ComboBox20.Items.Add("Sacramento")
        ComboBox20.Items.Add("Progreso")
        ComboBox20.Items.Add("Juárez")
        ComboBox20.Items.Add("Nava")
        ComboBox20.Items.Add("Allende")
        ComboBox20.Items.Add("Hidalgo")
        ComboBox20.Items.Add("Torreón")
        ComboBox20.Items.Add("Zaragoza")
        ComboBox20.Items.Add("Jiménez")
        ComboBox20.Items.Add("Matamoros")
        ComboBox20.Items.Add("Arteaga")
        ComboBox20.Items.Add("Parras de la Fuente")
        ComboBox20.Items.Add("Abasolo")
        ComboBox20.Items.Add("Piedras Negras")
        ComboBox20.Items.Add("Ramos Arizpe")
        ComboBox20.Items.Add("San Pedro")
        ComboBox20.Items.Add("Morelos")
        ComboBox20.Items.Add("Guerrero")
        ComboBox20.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox20.Items.Add("Saltillo")
        ComboBox20.Items.Add("Escobedo")
        ComboBox20.Items.Add("Frontera")
        ComboBox20.Items.Add("Castaños")
        ComboBox20.Items.Add("Nueva Rosita")
        ComboBox20.Items.Add("Sabinas")
        ComboBox20.Items.Add("San Buenaventura")
        ComboBox21.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox21.Items.Add("Nadadores")
        ComboBox21.Items.Add("Sierra Mojada")
        ComboBox21.Items.Add("Ocampo")
        ComboBox21.Items.Add("Candela")
        ComboBox21.Items.Add("Lamadrid")
        ComboBox21.Items.Add("Monclova")
        ComboBox21.Items.Add("Viesca")
        ComboBox21.Items.Add("Villa Unión")
        ComboBox21.Items.Add("Ciudad Acuña")
        ComboBox21.Items.Add("Francisco I.Madero")
        ComboBox21.Items.Add("General Cepeda")
        ComboBox21.Items.Add("Sacramento")
        ComboBox21.Items.Add("Progreso")
        ComboBox21.Items.Add("Juárez")
        ComboBox21.Items.Add("Nava")
        ComboBox21.Items.Add("Allende")
        ComboBox21.Items.Add("Hidalgo")
        ComboBox21.Items.Add("Torreón")
        ComboBox21.Items.Add("Zaragoza")
        ComboBox21.Items.Add("Jiménez")
        ComboBox21.Items.Add("Matamoros")
        ComboBox21.Items.Add("Arteaga")
        ComboBox21.Items.Add("Parras de la Fuente")
        ComboBox21.Items.Add("Abasolo")
        ComboBox21.Items.Add("Piedras Negras")
        ComboBox21.Items.Add("Ramos Arizpe")
        ComboBox21.Items.Add("San Pedro")
        ComboBox21.Items.Add("Morelos")
        ComboBox21.Items.Add("Guerrero")
        ComboBox21.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox21.Items.Add("Saltillo")
        ComboBox21.Items.Add("Escobedo")
        ComboBox21.Items.Add("Frontera")
        ComboBox21.Items.Add("Castaños")
        ComboBox21.Items.Add("Nueva Rosita")
        ComboBox21.Items.Add("Sabinas")
        ComboBox21.Items.Add("San Buenaventura")
        ComboBox22.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox22.Items.Add("Nadadores")
        ComboBox22.Items.Add("Sierra Mojada")
        ComboBox22.Items.Add("Ocampo")
        ComboBox22.Items.Add("Candela")
        ComboBox22.Items.Add("Lamadrid")
        ComboBox22.Items.Add("Monclova")
        ComboBox22.Items.Add("Viesca")
        ComboBox22.Items.Add("Villa Unión")
        ComboBox22.Items.Add("Ciudad Acuña")
        ComboBox22.Items.Add("Francisco I.Madero")
        ComboBox22.Items.Add("General Cepeda")
        ComboBox22.Items.Add("Sacramento")
        ComboBox22.Items.Add("Progreso")
        ComboBox22.Items.Add("Juárez")
        ComboBox22.Items.Add("Nava")
        ComboBox22.Items.Add("Allende")
        ComboBox22.Items.Add("Hidalgo")
        ComboBox22.Items.Add("Torreón")
        ComboBox22.Items.Add("Zaragoza")
        ComboBox22.Items.Add("Jiménez")
        ComboBox22.Items.Add("Matamoros")
        ComboBox22.Items.Add("Arteaga")
        ComboBox22.Items.Add("Parras de la Fuente")
        ComboBox22.Items.Add("Abasolo")
        ComboBox22.Items.Add("Piedras Negras")
        ComboBox22.Items.Add("Ramos Arizpe")
        ComboBox22.Items.Add("San Pedro")
        ComboBox22.Items.Add("Morelos")
        ComboBox22.Items.Add("Guerrero")
        ComboBox22.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox22.Items.Add("Saltillo")
        ComboBox22.Items.Add("Escobedo")
        ComboBox22.Items.Add("Frontera")
        ComboBox22.Items.Add("Castaños")
        ComboBox22.Items.Add("Nueva Rosita")
        ComboBox22.Items.Add("Sabinas")
        ComboBox22.Items.Add("San Buenaventura")
        ComboBox23.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox23.Items.Add("Nadadores")
        ComboBox23.Items.Add("Sierra Mojada")
        ComboBox23.Items.Add("Ocampo")
        ComboBox23.Items.Add("Candela")
        ComboBox23.Items.Add("Lamadrid")
        ComboBox23.Items.Add("Monclova")
        ComboBox23.Items.Add("Viesca")
        ComboBox23.Items.Add("Villa Unión")
        ComboBox23.Items.Add("Ciudad Acuña")
        ComboBox23.Items.Add("Francisco I.Madero")
        ComboBox23.Items.Add("General Cepeda")
        ComboBox23.Items.Add("Sacramento")
        ComboBox23.Items.Add("Progreso")
        ComboBox23.Items.Add("Juárez")
        ComboBox23.Items.Add("Nava")
        ComboBox23.Items.Add("Allende")
        ComboBox23.Items.Add("Hidalgo")
        ComboBox23.Items.Add("Torreón")
        ComboBox23.Items.Add("Zaragoza")
        ComboBox23.Items.Add("Jiménez")
        ComboBox23.Items.Add("Matamoros")
        ComboBox23.Items.Add("Arteaga")
        ComboBox23.Items.Add("Parras de la Fuente")
        ComboBox23.Items.Add("Abasolo")
        ComboBox23.Items.Add("Piedras Negras")
        ComboBox23.Items.Add("Ramos Arizpe")
        ComboBox23.Items.Add("San Pedro")
        ComboBox23.Items.Add("Morelos")
        ComboBox23.Items.Add("Guerrero")
        ComboBox23.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox23.Items.Add("Saltillo")
        ComboBox23.Items.Add("Escobedo")
        ComboBox23.Items.Add("Frontera")
        ComboBox23.Items.Add("Castaños")
        ComboBox23.Items.Add("Nueva Rosita")
        ComboBox23.Items.Add("Sabinas")
        ComboBox23.Items.Add("San Buenaventura")
        ComboBox24.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox24.Items.Add("Nadadores")
        ComboBox24.Items.Add("Sierra Mojada")
        ComboBox24.Items.Add("Ocampo")
        ComboBox24.Items.Add("Candela")
        ComboBox24.Items.Add("Lamadrid")
        ComboBox24.Items.Add("Monclova")
        ComboBox24.Items.Add("Viesca")
        ComboBox24.Items.Add("Villa Unión")
        ComboBox24.Items.Add("Ciudad Acuña")
        ComboBox24.Items.Add("Francisco I.Madero")
        ComboBox24.Items.Add("General Cepeda")
        ComboBox24.Items.Add("Sacramento")
        ComboBox24.Items.Add("Progreso")
        ComboBox24.Items.Add("Juárez")
        ComboBox24.Items.Add("Nava")
        ComboBox24.Items.Add("Allende")
        ComboBox24.Items.Add("Hidalgo")
        ComboBox24.Items.Add("Torreón")
        ComboBox24.Items.Add("Zaragoza")
        ComboBox24.Items.Add("Jiménez")
        ComboBox24.Items.Add("Matamoros")
        ComboBox24.Items.Add("Arteaga")
        ComboBox24.Items.Add("Parras de la Fuente")
        ComboBox24.Items.Add("Abasolo")
        ComboBox24.Items.Add("Piedras Negras")
        ComboBox24.Items.Add("Ramos Arizpe")
        ComboBox24.Items.Add("San Pedro")
        ComboBox24.Items.Add("Morelos")
        ComboBox24.Items.Add("Guerrero")
        ComboBox24.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox24.Items.Add("Saltillo")
        ComboBox24.Items.Add("Escobedo")
        ComboBox24.Items.Add("Frontera")
        ComboBox24.Items.Add("Castaños")
        ComboBox24.Items.Add("Nueva Rosita")
        ComboBox24.Items.Add("Sabinas")
        ComboBox24.Items.Add("San Buenaventura")
        ComboBox25.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox25.Items.Add("Nadadores")
        ComboBox25.Items.Add("Sierra Mojada")
        ComboBox25.Items.Add("Ocampo")
        ComboBox25.Items.Add("Candela")
        ComboBox25.Items.Add("Lamadrid")
        ComboBox25.Items.Add("Monclova")
        ComboBox25.Items.Add("Viesca")
        ComboBox25.Items.Add("Villa Unión")
        ComboBox25.Items.Add("Ciudad Acuña")
        ComboBox25.Items.Add("Francisco I.Madero")
        ComboBox25.Items.Add("General Cepeda")
        ComboBox25.Items.Add("Sacramento")
        ComboBox25.Items.Add("Progreso")
        ComboBox25.Items.Add("Juárez")
        ComboBox25.Items.Add("Nava")
        ComboBox25.Items.Add("Allende")
        ComboBox25.Items.Add("Hidalgo")
        ComboBox25.Items.Add("Torreón")
        ComboBox25.Items.Add("Zaragoza")
        ComboBox25.Items.Add("Jiménez")
        ComboBox25.Items.Add("Matamoros")
        ComboBox25.Items.Add("Arteaga")
        ComboBox25.Items.Add("Parras de la Fuente")
        ComboBox25.Items.Add("Abasolo")
        ComboBox25.Items.Add("Piedras Negras")
        ComboBox25.Items.Add("Ramos Arizpe")
        ComboBox25.Items.Add("San Pedro")
        ComboBox25.Items.Add("Morelos")
        ComboBox25.Items.Add("Guerrero")
        ComboBox25.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox25.Items.Add("Saltillo")
        ComboBox25.Items.Add("Escobedo")
        ComboBox25.Items.Add("Frontera")
        ComboBox25.Items.Add("Castaños")
        ComboBox25.Items.Add("Nueva Rosita")
        ComboBox25.Items.Add("Sabinas")
        ComboBox25.Items.Add("San Buenaventura")
        ComboBox26.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox26.Items.Add("Nadadores")
        ComboBox26.Items.Add("Sierra Mojada")
        ComboBox26.Items.Add("Ocampo")
        ComboBox26.Items.Add("Candela")
        ComboBox26.Items.Add("Lamadrid")
        ComboBox26.Items.Add("Monclova")
        ComboBox26.Items.Add("Viesca")
        ComboBox26.Items.Add("Villa Unión")
        ComboBox26.Items.Add("Ciudad Acuña")
        ComboBox26.Items.Add("Francisco I.Madero")
        ComboBox26.Items.Add("General Cepeda")
        ComboBox26.Items.Add("Sacramento")
        ComboBox26.Items.Add("Progreso")
        ComboBox26.Items.Add("Juárez")
        ComboBox26.Items.Add("Nava")
        ComboBox26.Items.Add("Allende")
        ComboBox26.Items.Add("Hidalgo")
        ComboBox26.Items.Add("Torreón")
        ComboBox26.Items.Add("Zaragoza")
        ComboBox26.Items.Add("Jiménez")
        ComboBox26.Items.Add("Matamoros")
        ComboBox26.Items.Add("Arteaga")
        ComboBox26.Items.Add("Parras de la Fuente")
        ComboBox26.Items.Add("Abasolo")
        ComboBox26.Items.Add("Piedras Negras")
        ComboBox26.Items.Add("Ramos Arizpe")
        ComboBox26.Items.Add("San Pedro")
        ComboBox26.Items.Add("Morelos")
        ComboBox26.Items.Add("Guerrero")
        ComboBox26.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox26.Items.Add("Saltillo")
        ComboBox26.Items.Add("Escobedo")
        ComboBox26.Items.Add("Frontera")
        ComboBox26.Items.Add("Castaños")
        ComboBox26.Items.Add("Nueva Rosita")
        ComboBox26.Items.Add("Sabinas")
        ComboBox26.Items.Add("San Buenaventura")
        ComboBox27.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox27.Items.Add("Nadadores")
        ComboBox27.Items.Add("Sierra Mojada")
        ComboBox27.Items.Add("Ocampo")
        ComboBox27.Items.Add("Candela")
        ComboBox27.Items.Add("Lamadrid")
        ComboBox27.Items.Add("Monclova")
        ComboBox27.Items.Add("Viesca")
        ComboBox27.Items.Add("Villa Unión")
        ComboBox27.Items.Add("Ciudad Acuña")
        ComboBox27.Items.Add("Francisco I.Madero")
        ComboBox27.Items.Add("General Cepeda")
        ComboBox27.Items.Add("Sacramento")
        ComboBox27.Items.Add("Progreso")
        ComboBox27.Items.Add("Juárez")
        ComboBox27.Items.Add("Nava")
        ComboBox27.Items.Add("Allende")
        ComboBox27.Items.Add("Hidalgo")
        ComboBox27.Items.Add("Torreón")
        ComboBox27.Items.Add("Zaragoza")
        ComboBox27.Items.Add("Jiménez")
        ComboBox27.Items.Add("Matamoros")
        ComboBox27.Items.Add("Arteaga")
        ComboBox27.Items.Add("Parras de la Fuente")
        ComboBox27.Items.Add("Abasolo")
        ComboBox27.Items.Add("Piedras Negras")
        ComboBox27.Items.Add("Ramos Arizpe")
        ComboBox27.Items.Add("San Pedro")
        ComboBox27.Items.Add("Morelos")
        ComboBox27.Items.Add("Guerrero")
        ComboBox27.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox27.Items.Add("Saltillo")
        ComboBox27.Items.Add("Escobedo")
        ComboBox27.Items.Add("Frontera")
        ComboBox27.Items.Add("Castaños")
        ComboBox27.Items.Add("Nueva Rosita")
        ComboBox27.Items.Add("Sabinas")
        ComboBox27.Items.Add("San Buenaventura")
        ComboBox28.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox28.Items.Add("Nadadores")
        ComboBox28.Items.Add("Sierra Mojada")
        ComboBox28.Items.Add("Ocampo")
        ComboBox28.Items.Add("Candela")
        ComboBox28.Items.Add("Lamadrid")
        ComboBox28.Items.Add("Monclova")
        ComboBox28.Items.Add("Viesca")
        ComboBox28.Items.Add("Villa Unión")
        ComboBox28.Items.Add("Ciudad Acuña")
        ComboBox28.Items.Add("Francisco I.Madero")
        ComboBox28.Items.Add("General Cepeda")
        ComboBox28.Items.Add("Sacramento")
        ComboBox28.Items.Add("Progreso")
        ComboBox28.Items.Add("Juárez")
        ComboBox28.Items.Add("Nava")
        ComboBox28.Items.Add("Allende")
        ComboBox28.Items.Add("Hidalgo")
        ComboBox28.Items.Add("Torreón")
        ComboBox28.Items.Add("Zaragoza")
        ComboBox28.Items.Add("Jiménez")
        ComboBox28.Items.Add("Matamoros")
        ComboBox28.Items.Add("Arteaga")
        ComboBox28.Items.Add("Parras de la Fuente")
        ComboBox28.Items.Add("Abasolo")
        ComboBox28.Items.Add("Piedras Negras")
        ComboBox28.Items.Add("Ramos Arizpe")
        ComboBox28.Items.Add("San Pedro")
        ComboBox28.Items.Add("Morelos")
        ComboBox28.Items.Add("Guerrero")
        ComboBox28.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox28.Items.Add("Saltillo")
        ComboBox28.Items.Add("Escobedo")
        ComboBox28.Items.Add("Frontera")
        ComboBox28.Items.Add("Castaños")
        ComboBox28.Items.Add("Nueva Rosita")
        ComboBox28.Items.Add("Sabinas")
        ComboBox28.Items.Add("San Buenaventura")
        ComboBox29.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox29.Items.Add("Nadadores")
        ComboBox29.Items.Add("Sierra Mojada")
        ComboBox29.Items.Add("Ocampo")
        ComboBox29.Items.Add("Candela")
        ComboBox29.Items.Add("Lamadrid")
        ComboBox29.Items.Add("Monclova")
        ComboBox29.Items.Add("Viesca")
        ComboBox29.Items.Add("Villa Unión")
        ComboBox29.Items.Add("Ciudad Acuña")
        ComboBox29.Items.Add("Francisco I.Madero")
        ComboBox29.Items.Add("General Cepeda")
        ComboBox29.Items.Add("Sacramento")
        ComboBox29.Items.Add("Progreso")
        ComboBox29.Items.Add("Juárez")
        ComboBox29.Items.Add("Nava")
        ComboBox29.Items.Add("Allende")
        ComboBox29.Items.Add("Hidalgo")
        ComboBox29.Items.Add("Torreón")
        ComboBox29.Items.Add("Zaragoza")
        ComboBox29.Items.Add("Jiménez")
        ComboBox29.Items.Add("Matamoros")
        ComboBox29.Items.Add("Arteaga")
        ComboBox29.Items.Add("Parras de la Fuente")
        ComboBox29.Items.Add("Abasolo")
        ComboBox29.Items.Add("Piedras Negras")
        ComboBox29.Items.Add("Ramos Arizpe")
        ComboBox29.Items.Add("San Pedro")
        ComboBox29.Items.Add("Morelos")
        ComboBox29.Items.Add("Guerrero")
        ComboBox29.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox29.Items.Add("Saltillo")
        ComboBox29.Items.Add("Escobedo")
        ComboBox29.Items.Add("Frontera")
        ComboBox29.Items.Add("Castaños")
        ComboBox29.Items.Add("Nueva Rosita")
        ComboBox29.Items.Add("Sabinas")
        ComboBox29.Items.Add("San Buenaventura")
        ComboBox30.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox30.Items.Add("Nadadores")
        ComboBox30.Items.Add("Sierra Mojada")
        ComboBox30.Items.Add("Ocampo")
        ComboBox30.Items.Add("Candela")
        ComboBox30.Items.Add("Lamadrid")
        ComboBox30.Items.Add("Monclova")
        ComboBox30.Items.Add("Viesca")
        ComboBox30.Items.Add("Villa Unión")
        ComboBox30.Items.Add("Ciudad Acuña")
        ComboBox30.Items.Add("Francisco I.Madero")
        ComboBox30.Items.Add("General Cepeda")
        ComboBox30.Items.Add("Sacramento")
        ComboBox30.Items.Add("Progreso")
        ComboBox30.Items.Add("Juárez")
        ComboBox30.Items.Add("Nava")
        ComboBox30.Items.Add("Allende")
        ComboBox30.Items.Add("Hidalgo")
        ComboBox30.Items.Add("Torreón")
        ComboBox30.Items.Add("Zaragoza")
        ComboBox30.Items.Add("Jiménez")
        ComboBox30.Items.Add("Matamoros")
        ComboBox30.Items.Add("Arteaga")
        ComboBox30.Items.Add("Parras de la Fuente")
        ComboBox30.Items.Add("Abasolo")
        ComboBox30.Items.Add("Piedras Negras")
        ComboBox30.Items.Add("Ramos Arizpe")
        ComboBox30.Items.Add("San Pedro")
        ComboBox30.Items.Add("Morelos")
        ComboBox30.Items.Add("Guerrero")
        ComboBox30.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox30.Items.Add("Saltillo")
        ComboBox30.Items.Add("Escobedo")
        ComboBox30.Items.Add("Frontera")
        ComboBox30.Items.Add("Castaños")
        ComboBox30.Items.Add("Nueva Rosita")
        ComboBox30.Items.Add("Sabinas")
        ComboBox30.Items.Add("San Buenaventura")
        ComboBox31.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox31.Items.Add("Nadadores")
        ComboBox31.Items.Add("Sierra Mojada")
        ComboBox31.Items.Add("Ocampo")
        ComboBox31.Items.Add("Candela")
        ComboBox31.Items.Add("Lamadrid")
        ComboBox31.Items.Add("Monclova")
        ComboBox31.Items.Add("Viesca")
        ComboBox31.Items.Add("Villa Unión")
        ComboBox31.Items.Add("Ciudad Acuña")
        ComboBox31.Items.Add("Francisco I.Madero")
        ComboBox31.Items.Add("General Cepeda")
        ComboBox31.Items.Add("Sacramento")
        ComboBox31.Items.Add("Progreso")
        ComboBox31.Items.Add("Juárez")
        ComboBox31.Items.Add("Nava")
        ComboBox31.Items.Add("Allende")
        ComboBox31.Items.Add("Hidalgo")
        ComboBox31.Items.Add("Torreón")
        ComboBox31.Items.Add("Zaragoza")
        ComboBox31.Items.Add("Jiménez")
        ComboBox31.Items.Add("Matamoros")
        ComboBox31.Items.Add("Arteaga")
        ComboBox31.Items.Add("Parras de la Fuente")
        ComboBox31.Items.Add("Abasolo")
        ComboBox31.Items.Add("Piedras Negras")
        ComboBox31.Items.Add("Ramos Arizpe")
        ComboBox31.Items.Add("San Pedro")
        ComboBox31.Items.Add("Morelos")
        ComboBox31.Items.Add("Guerrero")
        ComboBox31.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox31.Items.Add("Saltillo")
        ComboBox31.Items.Add("Escobedo")
        ComboBox31.Items.Add("Frontera")
        ComboBox31.Items.Add("Castaños")
        ComboBox31.Items.Add("Nueva Rosita")
        ComboBox31.Items.Add("Sabinas")
        ComboBox31.Items.Add("San Buenaventura")
        ComboBox32.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox32.Items.Add("Nadadores")
        ComboBox32.Items.Add("Sierra Mojada")
        ComboBox32.Items.Add("Ocampo")
        ComboBox32.Items.Add("Candela")
        ComboBox32.Items.Add("Lamadrid")
        ComboBox32.Items.Add("Monclova")
        ComboBox32.Items.Add("Viesca")
        ComboBox32.Items.Add("Villa Unión")
        ComboBox32.Items.Add("Ciudad Acuña")
        ComboBox32.Items.Add("Francisco I.Madero")
        ComboBox32.Items.Add("General Cepeda")
        ComboBox32.Items.Add("Sacramento")
        ComboBox32.Items.Add("Progreso")
        ComboBox32.Items.Add("Juárez")
        ComboBox32.Items.Add("Nava")
        ComboBox32.Items.Add("Allende")
        ComboBox32.Items.Add("Hidalgo")
        ComboBox32.Items.Add("Torreón")
        ComboBox32.Items.Add("Zaragoza")
        ComboBox32.Items.Add("Jiménez")
        ComboBox32.Items.Add("Matamoros")
        ComboBox32.Items.Add("Arteaga")
        ComboBox32.Items.Add("Parras de la Fuente")
        ComboBox32.Items.Add("Abasolo")
        ComboBox32.Items.Add("Piedras Negras")
        ComboBox32.Items.Add("Ramos Arizpe")
        ComboBox32.Items.Add("San Pedro")
        ComboBox32.Items.Add("Morelos")
        ComboBox32.Items.Add("Guerrero")
        ComboBox32.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox32.Items.Add("Saltillo")
        ComboBox32.Items.Add("Escobedo")
        ComboBox32.Items.Add("Frontera")
        ComboBox32.Items.Add("Castaños")
        ComboBox32.Items.Add("Nueva Rosita")
        ComboBox32.Items.Add("Sabinas")
        ComboBox32.Items.Add("San Buenaventura")
        ComboBox33.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox33.Items.Add("Nadadores")
        ComboBox33.Items.Add("Sierra Mojada")
        ComboBox33.Items.Add("Ocampo")
        ComboBox33.Items.Add("Candela")
        ComboBox33.Items.Add("Lamadrid")
        ComboBox33.Items.Add("Monclova")
        ComboBox33.Items.Add("Viesca")
        ComboBox33.Items.Add("Villa Unión")
        ComboBox33.Items.Add("Ciudad Acuña")
        ComboBox33.Items.Add("Francisco I.Madero")
        ComboBox33.Items.Add("General Cepeda")
        ComboBox33.Items.Add("Sacramento")
        ComboBox33.Items.Add("Progreso")
        ComboBox33.Items.Add("Juárez")
        ComboBox33.Items.Add("Nava")
        ComboBox33.Items.Add("Allende")
        ComboBox33.Items.Add("Hidalgo")
        ComboBox33.Items.Add("Torreón")
        ComboBox33.Items.Add("Zaragoza")
        ComboBox33.Items.Add("Jiménez")
        ComboBox33.Items.Add("Matamoros")
        ComboBox33.Items.Add("Arteaga")
        ComboBox33.Items.Add("Parras de la Fuente")
        ComboBox33.Items.Add("Abasolo")
        ComboBox33.Items.Add("Piedras Negras")
        ComboBox33.Items.Add("Ramos Arizpe")
        ComboBox33.Items.Add("San Pedro")
        ComboBox33.Items.Add("Morelos")
        ComboBox33.Items.Add("Guerrero")
        ComboBox33.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox33.Items.Add("Saltillo")
        ComboBox33.Items.Add("Escobedo")
        ComboBox33.Items.Add("Frontera")
        ComboBox33.Items.Add("Castaños")
        ComboBox33.Items.Add("Nueva Rosita")
        ComboBox33.Items.Add("Sabinas")
        ComboBox33.Items.Add("San Buenaventura")
        ComboBox34.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox34.Items.Add("Nadadores")
        ComboBox34.Items.Add("Sierra Mojada")
        ComboBox34.Items.Add("Ocampo")
        ComboBox34.Items.Add("Candela")
        ComboBox34.Items.Add("Lamadrid")
        ComboBox34.Items.Add("Monclova")
        ComboBox34.Items.Add("Viesca")
        ComboBox34.Items.Add("Villa Unión")
        ComboBox34.Items.Add("Ciudad Acuña")
        ComboBox34.Items.Add("Francisco I.Madero")
        ComboBox34.Items.Add("General Cepeda")
        ComboBox34.Items.Add("Sacramento")
        ComboBox34.Items.Add("Progreso")
        ComboBox34.Items.Add("Juárez")
        ComboBox34.Items.Add("Nava")
        ComboBox34.Items.Add("Allende")
        ComboBox34.Items.Add("Hidalgo")
        ComboBox34.Items.Add("Torreón")
        ComboBox34.Items.Add("Zaragoza")
        ComboBox34.Items.Add("Jiménez")
        ComboBox34.Items.Add("Matamoros")
        ComboBox34.Items.Add("Arteaga")
        ComboBox34.Items.Add("Parras de la Fuente")
        ComboBox34.Items.Add("Abasolo")
        ComboBox34.Items.Add("Piedras Negras")
        ComboBox34.Items.Add("Ramos Arizpe")
        ComboBox34.Items.Add("San Pedro")
        ComboBox34.Items.Add("Morelos")
        ComboBox34.Items.Add("Guerrero")
        ComboBox34.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox34.Items.Add("Saltillo")
        ComboBox34.Items.Add("Escobedo")
        ComboBox34.Items.Add("Frontera")
        ComboBox34.Items.Add("Castaños")
        ComboBox34.Items.Add("Nueva Rosita")
        ComboBox34.Items.Add("Sabinas")
        ComboBox34.Items.Add("San Buenaventura")
        ComboBox35.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox35.Items.Add("Nadadores")
        ComboBox35.Items.Add("Sierra Mojada")
        ComboBox35.Items.Add("Ocampo")
        ComboBox35.Items.Add("Candela")
        ComboBox35.Items.Add("Lamadrid")
        ComboBox35.Items.Add("Monclova")
        ComboBox35.Items.Add("Viesca")
        ComboBox35.Items.Add("Villa Unión")
        ComboBox35.Items.Add("Ciudad Acuña")
        ComboBox35.Items.Add("Francisco I.Madero")
        ComboBox35.Items.Add("General Cepeda")
        ComboBox35.Items.Add("Sacramento")
        ComboBox35.Items.Add("Progreso")
        ComboBox35.Items.Add("Juárez")
        ComboBox35.Items.Add("Nava")
        ComboBox35.Items.Add("Allende")
        ComboBox35.Items.Add("Hidalgo")
        ComboBox35.Items.Add("Torreón")
        ComboBox35.Items.Add("Zaragoza")
        ComboBox35.Items.Add("Jiménez")
        ComboBox35.Items.Add("Matamoros")
        ComboBox35.Items.Add("Arteaga")
        ComboBox35.Items.Add("Parras de la Fuente")
        ComboBox35.Items.Add("Abasolo")
        ComboBox35.Items.Add("Piedras Negras")
        ComboBox35.Items.Add("Ramos Arizpe")
        ComboBox35.Items.Add("San Pedro")
        ComboBox35.Items.Add("Morelos")
        ComboBox35.Items.Add("Guerrero")
        ComboBox35.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox35.Items.Add("Saltillo")
        ComboBox35.Items.Add("Escobedo")
        ComboBox35.Items.Add("Frontera")
        ComboBox35.Items.Add("Castaños")
        ComboBox35.Items.Add("Nueva Rosita")
        ComboBox35.Items.Add("Sabinas")
        ComboBox35.Items.Add("San Buenaventura")
        ComboBox36.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox36.Items.Add("Nadadores")
        ComboBox36.Items.Add("Sierra Mojada")
        ComboBox36.Items.Add("Ocampo")
        ComboBox36.Items.Add("Candela")
        ComboBox36.Items.Add("Lamadrid")
        ComboBox36.Items.Add("Monclova")
        ComboBox36.Items.Add("Viesca")
        ComboBox36.Items.Add("Villa Unión")
        ComboBox36.Items.Add("Ciudad Acuña")
        ComboBox36.Items.Add("Francisco I.Madero")
        ComboBox36.Items.Add("General Cepeda")
        ComboBox36.Items.Add("Sacramento")
        ComboBox36.Items.Add("Progreso")
        ComboBox36.Items.Add("Juárez")
        ComboBox36.Items.Add("Nava")
        ComboBox36.Items.Add("Allende")
        ComboBox36.Items.Add("Hidalgo")
        ComboBox36.Items.Add("Torreón")
        ComboBox36.Items.Add("Zaragoza")
        ComboBox36.Items.Add("Jiménez")
        ComboBox36.Items.Add("Matamoros")
        ComboBox36.Items.Add("Arteaga")
        ComboBox36.Items.Add("Parras de la Fuente")
        ComboBox36.Items.Add("Abasolo")
        ComboBox36.Items.Add("Piedras Negras")
        ComboBox36.Items.Add("Ramos Arizpe")
        ComboBox36.Items.Add("San Pedro")
        ComboBox36.Items.Add("Morelos")
        ComboBox36.Items.Add("Guerrero")
        ComboBox36.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox36.Items.Add("Saltillo")
        ComboBox36.Items.Add("Escobedo")
        ComboBox36.Items.Add("Frontera")
        ComboBox36.Items.Add("Castaños")
        ComboBox36.Items.Add("Nueva Rosita")
        ComboBox36.Items.Add("Sabinas")
        ComboBox36.Items.Add("San Buenaventura")
        ComboBox37.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox37.Items.Add("Nadadores")
        ComboBox37.Items.Add("Sierra Mojada")
        ComboBox37.Items.Add("Ocampo")
        ComboBox37.Items.Add("Candela")
        ComboBox37.Items.Add("Lamadrid")
        ComboBox37.Items.Add("Monclova")
        ComboBox37.Items.Add("Viesca")
        ComboBox37.Items.Add("Villa Unión")
        ComboBox37.Items.Add("Ciudad Acuña")
        ComboBox37.Items.Add("Francisco I.Madero")
        ComboBox37.Items.Add("General Cepeda")
        ComboBox37.Items.Add("Sacramento")
        ComboBox37.Items.Add("Progreso")
        ComboBox37.Items.Add("Juárez")
        ComboBox37.Items.Add("Nava")
        ComboBox37.Items.Add("Allende")
        ComboBox37.Items.Add("Hidalgo")
        ComboBox37.Items.Add("Torreón")
        ComboBox37.Items.Add("Zaragoza")
        ComboBox37.Items.Add("Jiménez")
        ComboBox37.Items.Add("Matamoros")
        ComboBox37.Items.Add("Arteaga")
        ComboBox37.Items.Add("Parras de la Fuente")
        ComboBox37.Items.Add("Abasolo")
        ComboBox37.Items.Add("Piedras Negras")
        ComboBox37.Items.Add("Ramos Arizpe")
        ComboBox37.Items.Add("San Pedro")
        ComboBox37.Items.Add("Morelos")
        ComboBox37.Items.Add("Guerrero")
        ComboBox37.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox37.Items.Add("Saltillo")
        ComboBox37.Items.Add("Escobedo")
        ComboBox37.Items.Add("Frontera")
        ComboBox37.Items.Add("Castaños")
        ComboBox37.Items.Add("Nueva Rosita")
        ComboBox37.Items.Add("Sabinas")
        ComboBox37.Items.Add("San Buenaventura")
        ComboBox38.Items.Add("Ciudad Melchor Muzquiz")
        ComboBox38.Items.Add("Nadadores")
        ComboBox38.Items.Add("Sierra Mojada")
        ComboBox38.Items.Add("Ocampo")
        ComboBox38.Items.Add("Candela")
        ComboBox38.Items.Add("Lamadrid")
        ComboBox38.Items.Add("Monclova")
        ComboBox38.Items.Add("Viesca")
        ComboBox38.Items.Add("Villa Unión")
        ComboBox38.Items.Add("Ciudad Acuña")
        ComboBox38.Items.Add("Francisco I.Madero")
        ComboBox38.Items.Add("General Cepeda")
        ComboBox38.Items.Add("Sacramento")
        ComboBox38.Items.Add("Progreso")
        ComboBox38.Items.Add("Juárez")
        ComboBox38.Items.Add("Nava")
        ComboBox38.Items.Add("Allende")
        ComboBox38.Items.Add("Hidalgo")
        ComboBox38.Items.Add("Torreón")
        ComboBox38.Items.Add("Zaragoza")
        ComboBox38.Items.Add("Jiménez")
        ComboBox38.Items.Add("Matamoros")
        ComboBox38.Items.Add("Arteaga")
        ComboBox38.Items.Add("Parras de la Fuente")
        ComboBox38.Items.Add("Abasolo")
        ComboBox38.Items.Add("Piedras Negras")
        ComboBox38.Items.Add("Ramos Arizpe")
        ComboBox38.Items.Add("San Pedro")
        ComboBox38.Items.Add("Morelos")
        ComboBox38.Items.Add("Guerrero")
        ComboBox38.Items.Add("Cuatro Ciénegas de Carranza")
        ComboBox38.Items.Add("Saltillo")
        ComboBox38.Items.Add("Escobedo")
        ComboBox38.Items.Add("Frontera")
        ComboBox38.Items.Add("Castaños")
        ComboBox38.Items.Add("Nueva Rosita")
        ComboBox38.Items.Add("Sabinas")
        ComboBox38.Items.Add("San Buenaventura")

    End Sub

    Private Sub ComboBox1_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox1.SelectedIndexChanged
        If ComboBox1.Text = "Abasolo" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox1.Enabled = False
            PicBoxYes1.Show()
        Else
            FrmNoCierto.Show()
            ComboBox1.Enabled = False
            PicBoxNo1.Show()
        End If
    End Sub

    Private Sub ComboBox2_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox2.SelectedIndexChanged
        If ComboBox2.Text = "Ciudad Acuña" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox2.Enabled = False
            PicBoxYes2.Show()
        Else
            FrmNoCierto.Show()
            ComboBox2.Enabled = False
            PicBoxNo2.Show()
        End If
    End Sub

    Private Sub ComboBox3_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox3.SelectedIndexChanged
        If ComboBox3.Text = "Allende" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox3.Enabled = False
            PicBoxYes3.Show()
        Else
            FrmNoCierto.Show()
            ComboBox3.Enabled = False
            PicBoxNo3.Show()
        End If
    End Sub

    Private Sub ComboBox4_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox4.SelectedIndexChanged
        If ComboBox4.Text = "Arteaga" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox4.Enabled = False
            PicBoxYes4.Show()
        Else
            FrmNoCierto.Show()
            ComboBox4.Enabled = False
            PicBoxNo4.Show()
        End If
    End Sub

    Private Sub ComboBox5_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox5.SelectedIndexChanged
        If ComboBox5.Text = "Candela" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox5.Enabled = False
            PicBoxYes5.Show()
        Else
            FrmNoCierto.Show()
            ComboBox5.Enabled = False
            PicBoxNo5.Show()
        End If
    End Sub

    Private Sub ComboBox6_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox6.SelectedIndexChanged
        If ComboBox6.Text = "Castaños" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox6.Enabled = False
            PicBoxYes6.Show()
        Else
            FrmNoCierto.Show()
            ComboBox6.Enabled = False
            PicBoxNo6.Show()
        End If
    End Sub

    Private Sub ComboBox7_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox7.SelectedIndexChanged
        If ComboBox7.Text = "Cuatro Ciénegas de Carranza" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox7.Enabled = False
            PicBoxYes7.Show()
        Else
            FrmNoCierto.Show()
            ComboBox7.Enabled = False
            PicBoxNo7.Show()
        End If
    End Sub

    Private Sub ComboBox8_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox8.SelectedIndexChanged
        If ComboBox8.Text = "Escobedo" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox8.Enabled = False
            PicBoxYes8.Show()
        Else
            FrmNoCierto.Show()
            ComboBox8.Enabled = False
            PicBoxNo8.Show()
        End If
    End Sub

    Private Sub ComboBox9_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox9.SelectedIndexChanged
        If ComboBox9.Text = "Francisco I.Madero" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox9.Enabled = False
            PicBoxYes9.Show()
        Else
            FrmNoCierto.Show()
            ComboBox9.Enabled = False
            PicBoxNo9.Show()
        End If
    End Sub

    Private Sub ComboBox10_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox10.SelectedIndexChanged
        If ComboBox10.Text = "Frontera" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox10.Enabled = False
            PicBoxYes10.Show()
        Else
            FrmNoCierto.Show()
            ComboBox10.Enabled = False
            PicBoxNo10.Show()
        End If
    End Sub

    Private Sub ComboBox11_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox11.SelectedIndexChanged
        If ComboBox11.Text = "General Cepeda" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox11.Enabled = False
            PicBoxYes11.Show()
        Else
            FrmNoCierto.Show()
            ComboBox11.Enabled = False
            PicBoxNo11.Show()
        End If
    End Sub

    Private Sub ComboBox12_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox12.SelectedIndexChanged
        If ComboBox12.Text = "Guerrero" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox12.Enabled = False
            PicBoxYes12.Show()
        Else
            FrmNoCierto.Show()
            ComboBox12.Enabled = False
            PicBoxNo12.Show()
        End If
    End Sub

    Private Sub ComboBox13_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox13.SelectedIndexChanged
        If ComboBox13.Text = "Hidalgo" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox13.Enabled = False
            PicBoxYes13.Show()
        Else
            FrmNoCierto.Show()
            ComboBox13.Enabled = False
            PicBoxNo13.Show()
        End If
    End Sub

    Private Sub ComboBox14_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox14.SelectedIndexChanged
        If ComboBox14.Text = "Jiménez" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox14.Enabled = False
            PicBoxYes14.Show()
        Else
            FrmNoCierto.Show()
            ComboBox14.Enabled = False
            PicBoxNo14.Show()
        End If
    End Sub

    Private Sub ComboBox15_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox15.SelectedIndexChanged
        If ComboBox15.Text = "Juárez" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox15.Enabled = False
            PicBoxYes15.Show()
        Else
            FrmNoCierto.Show()
            ComboBox15.Enabled = False
            PicBoxNo15.Show()
        End If
    End Sub

    Private Sub ComboBox16_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox16.SelectedIndexChanged
        If ComboBox16.Text = "Lamadrid" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox16.Enabled = False
            PicBoxYes16.Show()
        Else
            FrmNoCierto.Show()
            ComboBox16.Enabled = False
            PicBoxNo16.Show()
        End If
    End Sub

    Private Sub ComboBox17_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox17.SelectedIndexChanged
        If ComboBox17.Text = "Matamoros" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox17.Enabled = False
            PicBoxYes17.Show()
        Else
            FrmNoCierto.Show()
            ComboBox17.Enabled = False
            PicBoxNo17.Show()
        End If
    End Sub

    Private Sub ComboBox18_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox18.SelectedIndexChanged
        If ComboBox18.Text = "Monclova" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox18.Enabled = False
            PicBoxYes18.Show()
        Else
            FrmNoCierto.Show()
            ComboBox18.Enabled = False
            PicBoxNo18.Show()
        End If
    End Sub

    Private Sub ComboBox19_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox19.SelectedIndexChanged
        If ComboBox19.Text = "Morelos" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox19.Enabled = False
            PicBoxYes19.Show()
        Else
            FrmNoCierto.Show()
            ComboBox19.Enabled = False
            PicBoxNo19.Show()
        End If
    End Sub

    Private Sub ComboBox20_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox20.SelectedIndexChanged
        If ComboBox20.Text = "Ciudad Melchor Muzquiz" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox20.Enabled = False
            PicBoxYes20.Show()
        Else
            FrmNoCierto.Show()
            ComboBox20.Enabled = False
            PicBoxNo20.Show()
        End If
    End Sub

    Private Sub ComboBox21_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox21.SelectedIndexChanged
        If ComboBox21.Text = "Nadadores" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox21.Enabled = False
            PicBoxYes21.Show()
        Else
            FrmNoCierto.Show()
            ComboBox21.Enabled = False
            PicBoxNo21.Show()
        End If
    End Sub

    Private Sub ComboBox22_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox22.SelectedIndexChanged
        If ComboBox22.Text = "Nava" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox22.Enabled = False
            PicBoxYes22.Show()
        Else
            FrmNoCierto.Show()
            ComboBox22.Enabled = False
            PicBoxNo22.Show()
        End If
    End Sub

    Private Sub ComboBox23_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox23.SelectedIndexChanged
        If ComboBox23.Text = "Ocampo" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox23.Enabled = False
            PicBoxYes23.Show()
        Else
            FrmNoCierto.Show()
            ComboBox23.Enabled = False
            PicBoxNo23.Show()
        End If
    End Sub

    Private Sub ComboBox24_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox24.SelectedIndexChanged
        If ComboBox24.Text = "Parras de la Fuente" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox24.Enabled = False
            PicBoxYes24.Show()
        Else
            FrmNoCierto.Show()
            ComboBox24.Enabled = False
            PicBoxNo24.Show()
        End If
    End Sub

    Private Sub ComboBox25_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox25.SelectedIndexChanged
        If ComboBox25.Text = "Piedras Negras" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox25.Enabled = False
            PicBoxYes25.Show()
        Else
            FrmNoCierto.Show()
            ComboBox25.Enabled = False
            PicBoxNo25.Show()
        End If
    End Sub

    Private Sub ComboBox26_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox26.SelectedIndexChanged
        If ComboBox26.Text = "Progreso" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox26.Enabled = False
            PicBoxYes26.Show()
        Else
            FrmNoCierto.Show()
            ComboBox26.Enabled = False
            PicBoxNo26.Show()
        End If
    End Sub

    Private Sub ComboBox27_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox27.SelectedIndexChanged
        If ComboBox27.Text = "Ramos Arizpe" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox27.Enabled = False
            PicBoxYes27.Show()
        Else
            FrmNoCierto.Show()
            ComboBox27.Enabled = False
            PicBoxNo27.Show()
        End If
    End Sub

    Private Sub ComboBox28_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox28.SelectedIndexChanged
        If ComboBox28.Text = "Sabinas" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox28.Enabled = False
            PicBoxYes28.Show()
        Else
            FrmNoCierto.Show()
            ComboBox28.Enabled = False
            PicBoxNo28.Show()
        End If
    End Sub

    Private Sub ComboBox29_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox29.SelectedIndexChanged
        If ComboBox29.Text = "Sacramento" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox29.Enabled = False
            PicBoxYes29.Show()
        Else
            FrmNoCierto.Show()
            ComboBox29.Enabled = False
            PicBoxNo29.Show()
        End If
    End Sub

    Private Sub ComboBox30_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox30.SelectedIndexChanged
        If ComboBox30.Text = "Saltillo" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox30.Enabled = False
            PicBoxYes30.Show()
        Else
            FrmNoCierto.Show()
            ComboBox30.Enabled = False
            PicBoxNo30.Show()
        End If
    End Sub

    Private Sub ComboBox31_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox31.SelectedIndexChanged
        If ComboBox31.Text = "San Buenaventura" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox31.Enabled = False
            PicBoxYes31.Show()
        Else
            FrmNoCierto.Show()
            ComboBox31.Enabled = False
            PicBoxNo31.Show()
        End If
    End Sub

    Private Sub ComboBox32_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox32.SelectedIndexChanged
        If ComboBox32.Text = "Nueva Rosita" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox32.Enabled = False
            PicBoxYes32.Show()
        Else
            FrmNoCierto.Show()
            ComboBox32.Enabled = False
            PicBoxNo32.Show()
        End If
    End Sub

    Private Sub ComboBox33_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox33.SelectedIndexChanged
        If ComboBox33.Text = "San Pedro" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox33.Enabled = False
            PicBoxYes33.Show()
        Else
            FrmNoCierto.Show()
            ComboBox33.Enabled = False
            PicBoxNo33.Show()
        End If
    End Sub

    Private Sub ComboBox34_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox34.SelectedIndexChanged
        If ComboBox34.Text = "Sierra Mojada" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox34.Enabled = False
            PicBoxYes34.Show()
        Else
            FrmNoCierto.Show()
            ComboBox34.Enabled = False
            PicBoxNo34.Show()
        End If
    End Sub

    Private Sub ComboBox35_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox35.SelectedIndexChanged
        If ComboBox35.Text = "Torreón" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox35.Enabled = False
            PicBoxYes35.Show()
        Else
            FrmNoCierto.Show()
            ComboBox35.Enabled = False
            PicBoxNo35.Show()
        End If
    End Sub

    Private Sub ComboBox36_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox36.SelectedIndexChanged
        If ComboBox36.Text = "Viesca" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox36.Enabled = False
            PicBoxYes36.Show()
        Else
            FrmNoCierto.Show()
            ComboBox36.Enabled = False
            PicBoxNo36.Show()
        End If
    End Sub

    Private Sub ComboBox37_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox37.SelectedIndexChanged
        If ComboBox37.Text = "Villa Unión" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox37.Enabled = False
            PicBoxYes37.Show()
        Else
            FrmNoCierto.Show()
            ComboBox37.Enabled = False
            PicBoxNo37.Show()
        End If
    End Sub

    Private Sub ComboBox38_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ComboBox38.SelectedIndexChanged
        If ComboBox38.Text = "Zaragoza" Then
            MsgBox("Respuesta Correcta", MsgBoxStyle.Information, "Une y Aprende")
            ComboBox38.Enabled = False
            PicBoxYes38.Show()
        Else
            FrmNoCierto.Show()
            ComboBox38.Enabled = False
            PicBoxNo38.Show()
        End If
    End Sub
End Class

